### PR TITLE
Add authentication feature & style to devise views

### PR DESCRIPTION
**Pull request by danalvrz**
- Installed and setup devise.
- It is possible to register a new user.
- User logs in with a combination of email and password.
- Hashed password should are stored in the database.
- App asks for confirmation of email.
- Users can reset password.
- Added styling to register and log in views.

### CODE REVIEW

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi @danalvrz, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmsesay** [comment]
- [x] I encountered some issues when I tried making migration to test your applicaiton. Because of these errors, I was unable to test your authentication functionality.
The first error is coming from `20220331203215_add_user_ref_to_posts` at line 4.
Please see the screenshot below and try to amend this migration error.

Migration Error 1|
:---------------------:|
a2|

-  [x] Secondly, I got another migration error coming from this file `20220331204622_create_comment` stating that you forgot to add the `end` keyword for your change method.

Migration Error 2|
:--------------------:|
a1

**Comment by danalvrz** [comment]
Hey, @mmsesay! Thanks for the comments, I made the changes and restarted the db, ran the migrations and I'm not getting any errors now.

**Review by rotimiazeez — APPROVED** [review]
# Hi @danalvrz 👋, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
