### PR TITLE
Feature/capybara

### PR DESCRIPTION
**Pull request by danalvrz**
Used Capybara to write integration tests for:

- Users index
- Users show
- Post index
- Post show
- Login

### CODE REVIEW

**Review by ahmetbozaci — CHANGES_REQUESTED** [review]
# STATUS: Changes Required  ♻️


 @danalvrz  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.


### ♻️ Request changes ♻️

- [x] _Check the comments under the review._

- [x] Nice to add tests but ı am getting errors when running the test. Please fix it.

image

image

**You** can see the server is not working also. If you fix it probably tests will work.
image



___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏

almost

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by danalvrz** [comment]
hey @ahmetbozaci ! Thanks for the comments, I don't know why you got the error, but I removed the line you mentioned and ran the tests, all are passing on my end. I hope the changes I made will fix it for you too.
Screen Shot 2022-04-19 at 12 55 02

**Review by bimbolabuari — APPROVED** [review]
Hi @danalvrz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahmetbozaci** [comment]
> hey @ahmetbozaci ! Thanks for the comments, I don't know why you got the error, but I removed the line you mentioned and ran the tests, all are passing on my end. I hope the changes I made will fix it for you too. Screen Shot 2022-04-19 at 12 55 02

@danalvrz Yes, you can fix it like that. Also, make sure rails server is working or not.

**Pull request merged**
